host:
  app_url: http://localhost:3000
  api_url: http://localhost:8080
  listen: 0.0.0.0
  port: 8080

auth:
  jwt:
    expire: 86400  # 24 hours in seconds
    expire_group: 86400    # 24 hours in seconds

cors:
  allow_origins: ["*"]  # Allowed origins for CORS

log:
  level: "debug"  # Available levels: debug, info, warn, error, fatal, panic

db:
  sqlitepath: "./data.db"

mail:
  enabled: true
  templates_dir: "./templates/emails"
